# Vizdoom Config
episodes: 125
vizdoom-env: VizdoomDefendLine-v1

# Overall model parameters (Reference vizdoom docs)
latent-dim: 128
action-dim: 4
game-state-dim: 2

# Vae Parameters
vae:
  model-path: ./vae-best.pt
  train: False 
  training-params:
    batch-size: 16
    beta: 1e-2
    epochs: 50
    lr: 1e-4

mdnrnn:
  model-path: ./trained_models/latest_mdnrnn.pt
  train: True
  training-params:
    mixtures: 5
    hidden-dim: 32
    batch-size: 16
    epochs: 200
    lr: 5e-4
    lambda-reward: 5e-3
    lambda-done: 1
    seq-length: 32